### ISSUE TITLE
Deploy failed with Jekyll 4.3.3

### ISSUE THREAD

**Issue by cookiebody** [digitalocean/sample-jekyll#15]
Tried with branch version 4.3.3 #13 , always failed with the log:
```
 Running custom build command: bundle exec jekyll build -d ./public
[2024-04-16 16:51:30] │ Configuration file: /workspace/_config.yml
[2024-04-16 16:51:30] │             Source: /workspace
[2024-04-16 16:51:30] │        Destination: /workspace/public
[2024-04-16 16:51:30] │  Incremental build: disabled. Enable with --incremental
[2024-04-16 16:51:30] │       Generating... 
[2024-04-16 16:51:30] │        Jekyll Feed: Generating feed for posts
[2024-04-16 16:51:31] │ /layers/heroku_ruby/gems/vendor/bundle/ruby/3.1.0/gems/sass-embedded-1.75.0-x86_64-linux-musl/lib/sass/compiler/connection.rb:54: warning: /layers/heroku_ruby/gems/vendor/bundle/ruby/3.1.0/gems/sass-embedded-1.75.0-x86_64-linux-musl/ext/sass/dart-sass/src/dart: error while loading shared libraries: libc.musl-x86_64.so.1: cannot open shared object file: No such file or directory
[2024-04-16 16:51:31] │   Conversion error: Jekyll::Converters::Scss encountered an error while converting 'assets/main.scss':
[2024-04-16 16:51:31] │                     end of file reached
[2024-04-16 16:51:31] │                     ------------------------------------------------
[2024-04-16 16:51:31] │       Jekyll 4.3.3   Please append `--trace` to the `build` command 
[2024-04-16 16:51:31] │                      for any additional information or backtrace. 
[2024-04-16 16:51:31] │                     ------------------------------------------------
[2024-04-16 16:51:31] │ /layers/heroku_ruby/gems/vendor/bundle/ruby/3.1.0/gems/sass-embedded-1.75.0-x86_64-linux-musl/lib/sass/compiler/varint.rb:20:in `readbyte': end of file reached (EOFError)
[2024-04-16 16:51:31] │         from /layers/heroku_ruby/gems/vendor/bundle/ruby/3.1.0/gems/sass-embedded-1.75.0-x86_64-linux-musl/lib/sass/compiler/varint.rb:20:in `block in read'
[2024-04-16 16:51:31] │         from /layers/heroku_ruby/gems/vendor/bundle/ruby/3.1.0/gems/sass-embedded-1.75.0-x86_64-linux-musl/lib/sass/compiler/varint.rb:19:in `loop'
[2024-04-16 16:51:31] │         from /layers/heroku_ruby/gems/vendor/bundle/ruby/3.1.0/gems/sass-embedded-1.75.0-x86_64-linux-musl/lib/sass/compiler/varint.rb:19:in `read'
[2024-04-16 16:51:31] │         from /layers/heroku_ruby/gems/vendor/bundle/ruby/3.1.0/gems/sass-embedded-1.75.0-x86_64-linux-musl/lib/sass/compiler/connection.rb:39:in `block (2 levels) in initialize'
[2024-04-16 16:51:31] │         from /layers/heroku_ruby/gems/vendor/bundle/ruby/3.1.0/gems/sass-embedded-1.75.0-x86_64-linux-musl/lib/sass/compiler/connection.rb:38:in `loop'
[2024-04-16 16:51:31] │         from /layers/heroku_ruby/gems/vendor/bundle/ruby/3.1.0/gems/sass-embedded-1.75.0-x86_64-linux-musl/lib/sass/compiler/connection.rb:38:in `block in initialize'
[2024-04-16 16:51:31] │ building: exit status 1
[2024-04-16 16:51:31] │ ERROR: failed to build: exit status 1
[2024-04-16 16:51:31] │ 
[2024-04-16 16:51:31] │ 
[2024-04-16 16:51:31] │ For documentation on the buildpacks used to build your app, please see:
[2024-04-16 16:51:31] │ 
[2024-04-16 16:51:31] │    Ruby  v1.244.3  https://do.co/apps-buildpack-ruby
[2024-04-16 16:51:31] │ 
[2024-04-16 16:51:31] │  ✘ build failed
```

**Comment by cookiebody** [comment]
Does it occur due to the `bundle` [version being too old ](https://github.com/jekyll/jekyll/issues/9312)with the DigitalOcean app environment??
